### ISSUE TITLE
Duration (elapsed time) of previous jobs is incorrect

### ISSUE THREAD

**Issue by svengato** [legumeinfo/Funnotate#2]
Probably due to YAML serialization of start & end time as numbers with insufficient precision.

**Comment by svengato** [comment]
To fix this, I want to save the job metadata as an R data file instead of YAML (and same for upload metadata). Do you mind if I purge all of your old (test) jobs and uploads?

**Comment by svengato** [comment]
Never mind, I can represent them as date-time strings instead, though the computed job duration may be off by a second or two.

**Comment by adf-ncgr** [comment]
OK, but in any case there's no need to be careful with stuff relating to any of my test jobs

**Comment by svengato** [comment]
I will just go through the old jobs and add plausible start & end times.

**Comment by adf-ncgr** [comment]
I should also note that at this point I'm not overly concerned about precision when it comes to such metadata regarding job time statistics!

**Comment by svengato** [comment]
Done - see commit ea027f5.
