### ISSUE TITLE
would be nice to be able to collapse the list of usr sequences

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/Funnotate#25]
in order to be able to get the tree and MSA viewer to be adjacent. alternatively, one could imagine going golden layout and giving the user the freedom to arrange the components as they see fit.

**Comment by svengato** [comment]
"Five Go Mad with GoldenLayout"?

**Comment by svengato** [comment]
It looks like it would be complicated to get Shiny and Golden Layout to work together. How about just toggling the highlighted features?
  http://dev.lis.ncgr.org:50080/shiny/Funnotate/?job=P1X4F&family=L_4F5ZWF

**Comment by adf-ncgr** [comment]
yes, that's fine; but there will be no lashings of ginger beer distributed.

**Comment by svengato** [comment]
Not until we also hide the Vertical/Radial layout buttons and "You have focused on a subtree" elements?

**Comment by svengato** [comment]
The **Phylotree info** check box toggles display of all elements between the MSA viewer and phylotree (commit [7a53f74](https://github.com/legumeinfo/Funnotate/commit/7a53f74952c2477ee895046215f52bfa8764384b)).

If that is insufficient, we can look at GoldenLayout again later.
