### ISSUE TITLE
internal node popup should link to newer GCV

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/Funnotate#29]
Currently, clicking on an internal node gives you the option to get a multi-alignment in GCV which is good but it is pointing to an older version of GCV. At some point we should try to get this to use a gene set linkout service, but for now it would be good to just switch it from what it currently references:
https://legacy.legumeinfo.org/lis_context_viewer/multi/gene1,gene2,gene3
to instead point to:
https://gcv.legumeinfo.org/gcv2/gene;lis=gene1,gene2,gene3

**Comment by svengato** [comment]
There is another problem: the gene names returned by the linkout are not full-yuck, so after replacing only the base URL we get (for example)
https://gcv.legumeinfo.org/gcv2/gene;lis=glyma.Glyma.20G085100,glyma.Glyma.10G134400,phavu.Phvul.007G270600,vigra.Vradi08g00870
which does not display any genes.

However, its full-yuck equivalent works as expected,
https://gcv.legumeinfo.org/gcv2/gene;lis=glyma.Wm82.gnm4.ann1.Glyma.20G085100,glyma.Wm82.gnm4.ann1.Glyma.10G134400,phavu.G19833.gnm2.ann1.Phvul.007G270600,vigra.VC1973A.gnm6.ann1.Vradi08g00870

A workaround is to substitute the full-yuck gene names as well, but I would likely be guessing at some of them.

**Comment by adf-ncgr** [comment]
I was actually curious as to where those non-full-yuck gene names were coming from to populate the older version of the URL since the trees now sport full-yuck protein ids. Looking at the code, I see it was another linkouts-type service:
`    var url = LINKOUTS_BASE_URL + '/famreps_links';
`
which I suppose was doing database lookups to deal with some of the nasty cases. Your version of database lookups is "ask intermine" which I suppose these days is supposed to be "ask intermine through graphql". Basically we just need to do a protein->gene lookup there. Hopefully not too difficult but it can wait for other higher priorities.

**Comment by svengato** [comment]
> A workaround is to substitute the full-yuck gene names as well, but I would likely be guessing at some of them.

I got these examples from GCV, let me know if there are any we do not need.
aesev.CIAT22838.gnm1.ann1.Ae08g11810
aradu.V14167.gnm1.ann1.Aradu.M206V
arahy.Tifrunner.gnm1.ann1.EV1AUE
araip.K30076.gnm1.ann1.Araip.Z4RG3
cajca.ICPL87119.gnm1.ann1.C.cajan_36467
cicar.CDCFrontier.gnm1.ann1.Ca_05015
glyd3.G1403.gnm1.ann1.Gto6g014270
glydo.G1134.gnm1.ann1.Gtt6g070884
glyfa.G1718.gnm1.ann1.Gfa6g014145
glyma.Wm82.gnm4.ann1.Glyma.06G088000
glyso.PI483463.gnm1.ann1.Glyso
glyst.G1974.gnm1.ann1.Gst6g013319
glysy.G1300.gnm1.ann1.Gsy6g013435
lotja.MG20.gnm3.ann1.Lj0g3v0166889
lupal.Amiga.gnm1.ann1.gene:Lalb_Chr08g0242951
lupan.Tanjil.gnm1.ann1.Lup028496
medsa.XinJiangDaYe.gnm1.ann1.MS.gene014606
medtr.A17_HM341.gnm4.ann2.Medtr3g110360
phaac.Frijol_Bayo.gnm1.ann1.Phacu.CVR.009G170700
phalu.G27455.gnm1.ann1.Pl09G0000091000
phavu.G19833.gnm2.ann1.Phvul.009G111700
pissa.Cameor.gnm1.ann1.Psat5g020400
tripr.MilvusB.gnm2.ann1.gene12462
trisu.Daliak.gnm2.ann1.Ts_27829
vigan.Gyeongwon.gnm3.ann1.Vang05g09870
vigra.VC1973A.gnm6.ann1.Vradi05g08580
vigun.IT97K-499-35.gnm1.ann1.Vigun

**Comment by svengato** [comment]
I missed your latest (famreps_links) comment - thinking about it now.

**Comment by svengato** [comment]
In the meantime, a crude workaround is in place at
http://dev.lis.ncgr.org:50080/shiny/Funnotate/

**Comment by adf-ncgr** [comment]
crude, but seemingly effective. However, if it is ultimately relying on a service from the legacy.legumeinfo.org site it will not work for much longer...

**Comment by svengato** [comment]
There are still several other references to legacy.legumeinfo.org in the code, I need to find replacements for those as well.

**Comment by adf-ncgr** [comment]
yes, now the leaf node popups are broken too, due to the removal of legacy. Those will also have to be converted to gene ids before they can use the linkout service, so I think the intermine query to convert from protein primary id to gene primary id is the first order of business.

**Comment by svengato** [comment]
Tentatively fixed in ui.R, let me know if they do not make sense.

http://dev.lis.ncgr.org:50080/shiny/Funnotate/
4. Assignment of [gene family](http://dev.lis.ncgr.org:50080/shiny/Funnotate/?search) &rarr; goes to our Gene Family Search page. (Should it?)

Any phylotree page, like http://dev.lis.ncgr.org:50080/shiny/Funnotate/?family=L_4F5ZWF
[Gene Family Help](http://dev.lis.ncgr.org:50080/shiny/Funnotate/static/gene-family-help.html) &rarr; goes to Gene Family Help page which is more or less copied from the legacy site's page, and needs updating. (Or should we just eliminate it?)

On that page,
The full family set is [available here.](data/public/Gene_families/) &rarr; Is there still a list of gene families anywhere? I do not see one in either the LIS or Legume Federation site, or in the data store.

**Comment by svengato** [comment]
> 4. Assignment of gene family

I guess this does not really need a link.

> Gene Family Help

Another option is to point this to a wiki page (to be created) in the Funnotate repository.

**Comment by svengato** [comment]
> I think the intermine query to convert from protein primary id to gene primary id is the first order of business.

Following examples in the InterMine API documentation, I wrote a JavaScript function to convert a protein (identifier) to its gene identifier, but cannot see how to load the imjs library. Next: try again tomorrow.

**Comment by svengato** [comment]
> cannot see how to load the imjs library

It looks like
`npm i imjs`
should work, but node.js is not present. Next: look into that.

**Comment by adf-ncgr** [comment]
Hi-
sorry for slow response. I am not too worried about the Help docs, although I guess keeping them as wiki pages in the github seems like a reasonable idea to me. 

With respect to location of the gene families it is currently:
https://data.legumeinfo.org/LEGUMES/Fabaceae/genefamilies/legume.genefam.fam1.M65K/

With respect to node.js I typically use nvm (node version manager) to handle it these days

**Comment by svengato** [comment]
> I am not too worried about the Help docs, although I guess keeping them as wiki pages in the github seems like a reasonable idea to me.

It does seem like a low priority that we can fix later.

> With respect to node.js I typically use nvm (node version manager) to handle it these days

It may not be necessary, I am in the middle of testing an alternative method.

**Comment by svengato** [comment]
Alternative method works, no need for node.js/nvm hacking. This converts protein identifiers to their gene identifier, at least for legume-related proteins if we call LegumeMine. Would there ever be more than one match?

**Comment by svengato** [comment]
Linkouts for legume-related leaf nodes are working again (in development Funnotate so far). For non-legumes it cannot look up the gene and just posts an error message. Next: internal nodes.

**Comment by svengato** [comment]
Restored the collapse/expand/focus/export actions for internal nodes, still working on linkouts.

**Comment by adf-ncgr** [comment]
The url format I gave at the beginning of the thread should work with full yuck gene ids; iirc the other targets were intermine list creation with gene or protein ids

**Comment by svengato** [comment]
> Do the internal node linkouts (including one to the GCV) still exist?

I meant `famreps_links?famreps=<...>`, but since that does not exist in this linkout service, what I can do is add a GCV multiple alignment linkout for internal nodes (assuming the node subtends at least one legume-related protein). This now works in the development Funnotate, for example
http://dev.lis.ncgr.org:50080/shiny/Funnotate/?family=L_4F5ZWF

Let me know if that is what you had in mind.

**Comment by svengato** [comment]
Resolved in commit a87895e.
