### ISSUE TITLE
Add text input to paste FASTA sequences into

### ISSUE THREAD

**Issue by svengato** [legumeinfo/Funnotate#3]
To complement loading them from a file.

**Comment by svengato** [comment]
There is now a choice of text v. file input.

**Comment by adf-ncgr** [comment]
looks good- for extra credit, it would be nifty to allow a POST to prepopulate the text area with posted sequence content, as Sam has done with Intermine -> SequenceServer, e.g. 
https://mines.legumeinfo.org/peanutmine/protein:Aradu.000JC.1
(click on little BLAST button to see in action)

NB: I haven't actually tested a POST against your URL to see if it already works...

Such a functionality would lead in the direction of my dream of being able to get genes we have assigned to families but not included in trees easily shipped off to lorax service without need for intermediate files or boor-joisy copy-paste operations.

**Comment by svengato** [comment]
You mean that InterMine (or other applications?) would have a Funnotate button (in addition to FASTA and BLAST) that would send the sequence directly to Funnotate? And Funnotate would have to handle such POST requests. I will look into that.

**Comment by adf-ncgr** [comment]
yes, something along those lines. In the long run it would be fun to extend the concept of the linkout service with POST-able services (ie a tool like Intermine might just ask it what could I POST FASTA protein sequences to? and present the user with the returned options- probably more complicated in reality than I'm imagining)

**Comment by svengato** [comment]
Text input added - see commit 812c79f.
Will handle POSTable services later.
