### ISSUE TITLE
Deduplicate identical sequences within FASTA input

### ISSUE THREAD

**Issue by svengato** [legumeinfo/Funnotate#30]
Otherwise Lorax returns a 406 error, and Funnotate prints "Error 406: Sequence upload for tree computation was not successful."

@adf-ncgr says:
> I seem to remember Joel maintaining that strictly identical sequences should not be allowed in tree-building procedures.

**Comment by adf-ncgr** [comment]
well, I just tested funnotate from the home page using two identical but differently named sequences and it worked just fine:
<img width="575" alt="image" src="https://github.com/legumeinfo/Funnotate/assets/2009605/ba81ed99-4a4b-4268-b51a-a21930b14f4c">

so, there goes my theory

**Comment by svengato** [comment]
The Error 406 problem should be fixed in commit 87aaa64. Should I close this issue with the 'wontfix' tag?

**Comment by adf-ncgr** [comment]
sound good
