### ISSUE TITLE
Funnotate job running for over 2 hrs!  AHRD problem?

### ISSUE THREAD

**Issue by jd-campbell** [legumeinfo/Funnotate#32]
I have submitted a funnotate job on LIS and it has been running the AHRD for over 2 hours now. The job ID is P3Q6Z and I submitted 6 fna sequences with 23582 total base pairs. 

So I am wondering if there is something wrong with the AHRD pipeline because it has never taken this long before. 

![Screen Shot 2024-03-12 at 13 03 03](https://github.com/legumeinfo/Funnotate/assets/13021601/bc9203bb-fc09-4e8e-9c65-2b3b354b2327)

**Comment by svengato** [comment]
It runs quickly on the development VM, can I restart the production one and have you try again?

**Comment by svengato** [comment]
The log file reports inability to create a temporary file at some point in the past, but it may not be related to this job.

**Comment by svengato** [comment]
I restarted it from the same upload (597). The new job is L4G1W, it completed in the usual time.
https://funnotate.legumeinfo.org/?job=L4G1W

**Comment by adf-ncgr** [comment]
Thanks @svengato I ran another job independently and it also worked fine. Sounds like it may have been a transient issue but let us know if it happens to you again @jd-campbell and thanks for reporting it. I'll leave the issue open for now but go ahead and close it if things seems to be working fine to you too.

**Comment by svengato** [comment]
Any update on this?

**Comment by StevenCannon-USDA** [comment]
Fwiw, I used the tool maybe 20 times on Monday successfully. It ran quickly for the sequences I was testing -- up to a dozen or so, of nucleotide gene sequence. I think it's OK to close this issue if you'd like, @svengato
