### ISSUE TITLE
Insert custom node into phylotree when user clicks [Tools icon] in Summary table row

### ISSUE THREAD

**Issue by svengato** [legumeinfo/Funnotate#6]
Preferably using containerized Lorax.

**Comment by svengato** [comment]
Built the Docker-containerized version of Lorax.

**Comment by svengato** [comment]
Do we really need the Cross References and Analysis views (sisters to the Phylogram view)? They do not seem useful or functional.

**Comment by adf-ncgr** [comment]
no, these are not important; thanks for asking about them

**Comment by svengato** [comment]
If all goes well, Lorax creates the phylotree and multiple sequence alignment. We display these directly in JavaScript, along with the taxa selector/pie chart.

There are known problems, which we will deal with later - see subsequent separate issues.

**Comment by svengato** [comment]
Fixed in commit fbd6556, along with issue #14.
